import { createHazardCard } from './factories'

export const hazardDeck = [
  createHazardCard(
    'Ion Storm',
    'ion-storm',
    'Engine icons cost +1 Fuel to commit at this Gate.',
    'Commit 2+ Engine crew.',
    'Fractured Engine',
    'Destinations that require Engine cost +1 Fuel.',
    'Electromagnetic interference',
  ),
  createHazardCard(
    'Dust Veil',
    'dust-veil',
    'The first crew committed contributes no icon at this Gate.',
    'Commit 2+ Science crew.',
    'Blinded Sensors',
    'The first crew committed at each Gate contributes no icon.',
    'Sensors blinded',
  ),
  createHazardCard(
    'Cold Reach',
    'cold-reach',
    'Tired crew cannot be readied during this sector.',
    'Commit 2+ Life crew.',
    'Cold Scarring',
    'Tired crew cannot be readied by rewards, Drift recovery, or Medbay Rehydrator.',
    'The cold creeps in',
  ),
  createHazardCard(
    'Echo Field',
    'echo-field',
    'MOTHER cannot be used at this Gate.',
    'Commit 2+ Nav crew.',
    'Jammed Comms',
    'At each Gate, 1 fewer MOTHER can be used.',
    'Comm channels jammed',
  ),
  createHazardCard(
    'Black Tide',
    'black-tide',
    'If Stress is 3+, add +1 crew slot to the Gate.',
    'Finish the Gate with Stress 2 or less.',
    'Flooded Corridors',
    'If Stress is 3+, future Gates add +1 crew slot.',
    'Existing pressure made visible',
  ),
  createHazardCard(
    'Fracture',
    'fracture',
    'One committed crew icon is ignored at this Gate.',
    'Commit a Mechanic crew.',
    'Crew Injury',
    'One committed crew icon is ignored at each Gate.',
    'A crew member is hurt',
  ),
  createHazardCard(
    'Silent Watch',
    'silent-watch',
    'No Drift card flips this sector; 3 Drift cards trigger when the Gate begins.',
    'Commit 1 extra crew beyond the Gate requirement.',
    'Bottled Entropy',
    '1 Drift card triggers when each future Gate begins.',
    'Bottled-up entropy',
  ),
  createHazardCard(
    'Hard Vacuum',
    'hard-vacuum',
    'Each missed icon at the Gate costs 2 MOTHER instead of 1.',
    'Pass the Gate without spending MOTHER.',
    'Thin Margins',
    'Each missed Gate icon costs +1 extra MOTHER.',
    'Margins are thin',
  ),
  createHazardCard(
    'Resonance',
    'resonance',
    'Each Blueprint trigger at this Gate adds 1 Stress.',
    'Pass the Gate without triggering a Blueprint.',
    'Resonant Hull',
    'Each future Blueprint trigger at a Gate adds 1 Stress.',
    'Stress for power',
  ),
  createHazardCard(
    'Ghost Signal',
    'ghost-signal',
    'Reveal one Destination from Sector Stops; it must be one of your 3 stops.',
    'Travel the revealed Destination before the Gate.',
    'Unanswered Signal',
    'Each future sector begins with a revealed Destination that should be traveled.',
    "A distress call you can't ignore",
  ),
  createHazardCard(
    'The Veil',
    'the-veil',
    'All Destinations in this sector cost +1 Fuel.',
    'Commit 2+ Nav crew.',
    'Veiled Charts',
    'All future Destinations cost +1 Fuel.',
    'The whole region is hard',
  ),
]
